server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6380
      timeout: 6000ms

  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1

                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/users

            # Order Service Route
            - id: order-service-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/orders/**

              filters:
                - StripPrefix=1

            # Payment Service Route
            - id: payment-service-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/payments/**

              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:

        slidingWindowSize: 5

        minimumNumberOfCalls: 3

        failureRateThreshold: 50

        waitDurationInOpenState: 10s

        permittedNumberOfCallsInHalfOpenState: 2

        automaticTransitionFromOpenToHalfOpenEnabled: true