server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6380
      timeout: 6000ms

  application:
    name: gateway-service


  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: lb://user-service

              predicates:
                - Path=/api/users/**

              filters:
                - StripPrefix=1

                - name: Retry
                  args:
                    retries: 3
                    statuses:
                      - BAD_GATEWAY
                      - INTERNAL_SERVER_ERROR
                      - SERVICE_UNAVAILABLE
                    methods:
                      - GET
                    backoff:
                      firstBackoff: 100ms
                      maxBackoff: 1000ms
                      factor: 2
                      basedOnPreviousValue: false

                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/users


            # Order Service Route
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**

              filters:
                - StripPrefix=1

            # Payment Service Route
            - id: payment-service-route
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**

              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

  metrics:
    tags:
      application: gateway-service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true

    instances:
      userServiceCircuitBreaker:

        slidingWindowSize: 5

        minimumNumberOfCalls: 3

        failureRateThreshold: 50

        waitDurationInOpenState: 10s

        permittedNumberOfCallsInHalfOpenState: 2

        automaticTransitionFromOpenToHalfOpenEnabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true