<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
         http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.gateway</groupId>
    <artifactId>api-gateway-system</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>api-gateway-system</name>

    <!-- Child Modules -->
    <modules>
        <module>gateway-service</module>
        <module>user-service</module>
        <module>order-service</module>
        <module>payment-service</module>
        <module>discovery-server</module>
    </modules>

    <!-- Common Versions -->
    <properties>
        <java.version>26</java.version>
        <spring.boot.version>4.0.6</spring.boot.version>
        <spring-cloud.version>2025.1.0</spring-cloud.version>
    </properties>

    <!-- Spring Boot Parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/>
    </parent>

    <!-- Spring Cloud BOM -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>